### ISSUE TITLE
运行deepFM出现以下问题

### ISSUE THREAD

**Issue by mostsuperman** [SSSxCCC/Recommender-System#10]
![image](https://user-images.githubusercontent.com/61960516/109627342-7e4bf380-7b7c-11eb-9ffb-78198718df75.png)
[](url)

**Comment by SSSxCCC** [comment]
这是由于新版tensorflow修改了key的名字导致了，刚刚一个提交修好了这个问题，请更新代码并使用python3.8和tensorflow2.4.1运行即可
