### ISSUE TITLE
如何自己去做一个数据集

### ISSUE THREAD

**Issue by neuliyiping** [SSSxCCC/Recommender-System#3]
比较好奇kg.txt文件是如何生成的？protege的来导出吗？还是如何操作得到？

**Comment by SSSxCCC** [comment]
这些文件是由MKR/RippleNet算法的作者在satori知识图谱中抽取出来的，然而satori知识图谱只有微软内部可以访问。我在知识图谱数据集中的readme文件里也已经写出了这些文件的出处。

**Comment by SSSxCCC** [comment]
知识图谱数据集由两个文件组成：kg.txt和item_id2entity_id.txt。kg.txt文件每行是一个三元组，item_id2entity_id.txt文件每行是物品id及其对应的知识图谱实体id。
想要自己构建知识图谱数据集，首先准备好知识图谱，然后针对数据集构建知识图谱，确定知识图谱包含哪些实体，并确定每个物品所对应的实体，最后将这些内容分别写入这两个文件，满足其格式即可。
构建好知识图谱数据集后，在kg目录创建文件夹，命名为这个数据集的名字，并将两个文件放入这个文件夹内，再在kg_loader.py里加入相应的代码来读取，就可以应用到推荐算法了。
