### ISSUE TITLE
为什么相同数据集不同规模下的索引item_index2entity_id.txt是一样

### ISSUE THREAD

**Issue by liu-call** [SSSxCCC/Recommender-System#4]
这里不同的图谱规模对应的索引表大小应该也是不一样的呀，不然处理后，得到相同的评分集，最后的结果就是一样的，然后分规模就没有用了，问一下这个索引表的生成规则是什么，有图谱所有的索引表吗

**Comment by SSSxCCC** [comment]
知识图谱数据集来自于MKR/RippleNet的作者，而原作者是从satori知识图谱抽取的，satori知识图谱不是公开的。所以知识图谱数据集具体怎么得到的我也不清楚哈。
分规模后即使索引是一样的，知识图谱大小不同，基于知识图谱的推荐算法从知识图谱中所能获取的信息也是不同的，所以还是会产生不同的推荐结果。
